name: Gherkin Linting

on: pull_request

jobs:

  gherkin-lint:
    name: Lint Gherkin Feature files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1
      - run: npm run lint
